In [3]:
import numpy as np

In [4]:
# Array of integers:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [5]:
# Create an array and manually set a type
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
# A list of lists in converted to a 2-dimensional array
original_list = [[1,2,3],[3,4,5],[6,7,8]]
two_dimensional_array = np.array(original_list)

In [7]:
two_dimensional_array

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
original_list

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [17]:
# An array of length 10, filled with 0:
np.zeros(10, dtype=int)
# An array of size 3x5 filled with 1.0 (float)
np.ones((3, 5), dtype=float)
# An array of size 3x5 filled with 3.14
np.full((3, 5), 3.14)
# An array containing a linear sequence starting at 0 and 
# going up to 20, with steps of 2
np.arange(0, 20, 2)
# An array of 5 numbers, linearly spaced between 0 and 1
np.linspace(0, 1, 5)
# An array of the given shape and populate it with random
# samples. You can also try using "randint" and "normal"
np.random.random((3, 3))
# The identity matrix of size 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.random((3, 3))

array([[0.7637378 , 0.83932184, 0.12720373],
       [0.9396704 , 0.99625493, 0.03695556],
       [0.23352571, 0.97654276, 0.48524829]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
x1
# 1-dimensional array
print("Number of dimensions: ", x1.ndim)
print("Shape: ", x1.shape)
print("Size: ", x1.size)
print("Type: ", x1.dtype)

Number of dimensions:  1
Shape:  (6,)
Size:  6
Type:  int64


In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
print(x1)
# The first element
print(x1[0])
# The last element
print(x1[-1])

x2 = np.random.randint(10, size=(3, 4))  
# 2-dimensional array
print(x2[0,1])

# You can also modify values:
x1[1] = "1000"
print(x1)

# Mind the type 
x1[1] = 3.14
print(x1)

[5 3 3 3 7 9]
5
9
1
[   5 1000    3    3    7    9]
[5 3 3 3 7 9]


In [32]:
x1

array([5, 3, 3, 3, 7, 9])

In [34]:
x1[::-1]

array([9, 7, 3, 3, 3, 5])

In [36]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [39]:
np.hstack([x, x])

array([1, 2, 3, 1, 2, 3])

In [42]:
def calculate_inverse(values):    
    output = np.empty(len(values))    
    for i in range(len(values)):        
        output[i] = 1.0 / values[i]    
    return output       

values = np.random.randint(1, 10, size=5)
print(calculate_inverse(values))

large_array = np.random.randint(1, 100, size=10000000)

# This is a Jupyter notebook tool to measure the execution
# time of an instruction
%timeit calculate_inverse(large_array)

[0.14285714 1.         0.25       0.5        0.11111111]
26.8 s ± 469 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [44]:
%timeit (1.0 / large_array)

43.5 ms ± 641 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [46]:
# Simple mathematics first
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
# Divide and round
print("x // 2 =", x // 2)  

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [48]:
#NumPy functions

x = [-2, -1, 1, 2]

print("Absolute value: ", np.abs(x))
print("Exponential: ", np.exp(x))
print("Logarithm: ", np.log(np.abs(x)))

Absolute value:  [2 1 1 2]
Exponential:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithm:  [0.69314718 0.         0.         0.69314718]


In [49]:
x = np.random.rand(3,3)
x > 0.5

array([[False, False,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [52]:
#You can couple this capability with  np.where, to return, 
#among all the elements of an array, the indexes of those 
#which have a certain property:

print(x)
np.where(x > 0.5)


[[0.08726554 0.15271945 0.7602133 ]
 [0.39544074 0.84987708 0.55322585]
 [0.57453392 0.02741157 0.94667587]]


(array([0, 1, 1, 2, 2]), array([2, 1, 2, 0, 2]))

In [54]:
L = np.random.random(100)
np.sum(L)

52.519144203322995

In [55]:
%timeit sum(large_array)

1.74 s ± 38.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [57]:

%timeit np.sum(large_array)


5.51 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [59]:
M = np.random.random((3, 4))
print(M)
# Note the syntax variable.function instead of 
# np.fonction(variable). Both are acceptable if
# variable is a Numpy array.
print("Sum of all elements of M: ", M.sum())
print("Sums of the columns of M: ", M.sum(axis=0))

[[0.56568047 0.82738261 0.15072872 0.47270518]
 [0.13023803 0.88017271 0.65464897 0.96873775]
 [0.56467145 0.74537141 0.50982551 0.70120265]]
Sum of all elements of M:  7.1713654570869805
Sums of the columns of M:  [1.26058994 2.45292673 1.3152032  2.14264558]


In [61]:
#You can create NumPy arrays from a Python List or manually.
#Indexing is used to access specific elements of an array.
#Slicing is used to extract a specific subset of a string. 
#NumPy functions include:
#Universal functions
#Boolean operations
#Aggregation
#Broadcasting

'You can create NumPy arrays from a Python List or manually.\nIndexing is used to access specific elements of an array.\nSlicing is used to extract a specific subset of a string. \nNumPy functions include:\nUniversal functions\nBoolean operations\nAggregation\nBroadcasting'